export const skillsData = [
  {
    name: 'marketing',
    keywords: [
      'marketing',
      'branding',
      'social media',
      'ads',
      'promotion',
      'sales',
      'التسويق',
      'الدعاية',
      'اعلان',
      'اعلانات',
      'مسوق',
      'بيع',
    ],
  },
  {
    name: 'coding',
    keywords: [
      'programming',
      'coding',
      'web',
      'frontend',
      'backend',
      'java',
      'script',
      'server',
      'software',
      'developer',
      'مطور',
      'مبرمج',
      'ويب',
      'موقع',
      'جافا سكريبت',
      'مهندس',
      'تطبيق',
    ],
  },
  {
    name: 'design',
    keywords: [
      'design',
      'graphic',
      'UI/UX',
      'illustration',
      'creative',
      'photoshop',
      'illustrator',
      'sketch',
      'adobe',
      'تصميم',
      'جرافيك',
      'فنان',
      'إبداعي',
      'فوتوشوب',
      'الرسام',
      'سكتش',
      'أدوبي',
      'مصمم',
    ],
  },
  {
    name: 'video editing',
    keywords: [
      'video editing',
      'video production',
      'editing software',
      'post-production',
      'video effects',
      'video transitions',
      'Adobe Premiere',
      'Final Cut Pro',
      'video montage',
      'motion graphics',
      'تحرير الفيديو',
      'إنتاج الفيديو',
      'برامج التحرير',
      'ما بعد الإنتاج',
      'تأثيرات الفيديو',
      'انتقالات الفيديو',
      'أدوبي بريمير',
      'فاينال كت برو',
      'مونتاج الفيديو',
      'رسوم متحركة',
    ],
  },
  {
    name: 'copy writing',
    keywords: [
      'copywriting',
      'content writing',
      'advertising copy',
      'marketing writing',
      'creative writing',
      'copy editing',
      'brand storytelling',
      'SEO writing',
      'sales copy',
      'persuasive writing',
      'كتابة النصوص',
      'كتابة المحتوى',
      'نسخ الإعلانات',
      'كتابة التسويق',
      'الكتابة الإبداعية',
      'تحرير النصوص',
      'سرد العلامات التجارية',
      'كتابة محتوى محرك البحث',
      'نصوص البيع',
      'الكتابة المقنعة',
    ],
  },
];
